import React from 'react';
import { Shield, Lock, FileText, Users, Bell, Eye, Edit, Download } from 'lucide-react';
import './privacyAndconfidentiality.css';

export default function PrivacyPage() {
  const sections = [
    {
      icon: Shield,
      title: "My Pledge Regarding Health Information",
      content: [
        "I understand that health information about you and your health care is personal. I am committed to protecting health information about you. I create a record of the care and services you receive from me. I need this record to provide you with quality care and to comply with certain legal requirements.",
        "This notice applies to all of the records of your care generated by this mental health care practice. This notice will tell you about the ways in which I may use and disclose health information about you. I also describe your rights to the health information I keep about you, and describe certain obligations I have regarding the use and disclosure of your health information."
      ],
      requirements: [
        'Make sure that protected health information ("PHI") that identifies you is kept private.',
        "Give you this notice of my legal duties and privacy practices with respect to health information.",
        "Follow the terms of the notice that is currently in effect.",
        "I can change the terms of this Notice, and such changes will apply to all information I have about you. The new Notice will be available upon request, in my office, and on my website."
      ]
    }
  ];

  const usageCategories = [
    {
      title: "For Treatment Payment, or Health Care Operations",
      description: "Federal privacy rules and regulations allow health care providers who have a direct treatment relationship with the client to use or disclose the client's personal health information without the client's written authorization, to carry out the health care provider's own treatment, payment or health care operations.",
      details: "I may also disclose your protected health information for the treatment activities of any health care provider. This too can be done without your written authorization. For example, if a clinician were to consult with another licensed health care provider about your condition, we would be permitted to use and disclose your personal health information, which is otherwise confidential, in order to assist the clinician in the diagnosis and treatment of your mental health condition."
    },
    {
      title: "Lawsuits and Disputes",
      description: "If you are involved in a lawsuit, I may disclose health information in response to a court or administrative order.",
      details: "I may also disclose health information about your child in response to a subpoena, discovery request, or other lawful process by someone else involved in the dispute, but only if efforts have been made to tell you about the request or to obtain an order protecting the information requested."
    }
  ];

  const authorizationRequired = [
    {
      title: "Psychotherapy Notes",
      points: [
        "For my use in treating you.",
        "For my use in training or supervising mental health practitioners to help them improve their skills in group, joint, family, or individual counseling or therapy.",
        "For my use in defending myself in legal proceedings instituted by you.",
        "For use by the Secretary of Health and Human Services to investigate my compliance with HIPAA.",
        "Required by law and the use or disclosure is limited to the requirements of such law.",
        "Required by law for certain health oversight activities pertaining to the originator of the psychotherapy notes.",
        "Required by a coroner who is performing duties authorized by law.",
        "Required to help avert a serious threat to the health and safety of others."
      ]
    },
    {
      title: "Marketing Purposes",
      description: "As a psychotherapist, I will not use or disclose your PHI for marketing purposes."
    },
    {
      title: "Sale of PHI",
      description: "As a psychotherapist, I will not sell your PHI in the regular course of my business."
    }
  ];

  const noAuthRequired = [
    "When disclosure is required by state or federal law, and the use or disclosure complies with and is limited to the relevant requirements of such law.",
    "For public health activities, including reporting suspected child, elder, or dependent adult abuse, or preventing or reducing a serious threat to anyone's health or safety.",
    "For health oversight activities, including audits and investigations.",
    "For judicial and administrative proceedings, including responding to a court or administrative order, although my preference is to obtain Authorization from you before doing so.",
    "For law enforcement purposes, including reporting crimes occurring on my premises.",
    "To coroners or medical examiners, when such individuals are performing duties authorized by law.",
    "For research purposes, including studying and comparing the mental health of patients who received one form of therapy versus those who received another form of therapy for the same condition.",
    "Specialized government functions, including, ensuring the proper execution of military missions; protecting the President of the United States; conducting intelligence or counter-intelligence operations; or, helping to ensure the safety of those working within or housed in correctional institutions.",
    "For workers' compensation purposes. Although my preference is to obtain an Authorization from you, I may provide your PHI in order to comply with workers' compensation laws.",
    "Appointment reminders and health-benefits or services. I may use and disclose your PHI to contact you to remind you that you have an appointment with me. I may also use and disclose your PHI to tell you about treatment alternatives, or other health care services or benefits that I offer."
  ];

  const yourRights = [
    {
      icon: Lock,
      title: "The Right to Request Limits on Uses and Disclosures of Your PHI",
      description: 'You have the right to ask me not to use or disclose certain PHI for treatment, payment, or health care operations purposes. I am not required to agree to your request, and I may say "no" if I believe it would affect your health care.'
    },
    {
      icon: FileText,
      title: "The Right to Request Restrictions for Out-of-Pocket Expenses Paid for In Full",
      description: "You have the right to request restrictions on disclosures of your PHI to health plans for payment or health care operations purposes if the PHI pertains solely to a health care item or a health care service that you have paid for out-of-pocket in full."
    },
    {
      icon: Bell,
      title: "The Right to Choose How I Send PHI to You",
      description: "You have the right to ask me to contact you in a specific way (for example, home or office phone) or to send mail to a different address, and I will agree to all reasonable requests."
    },
    {
      icon: Eye,
      title: "The Right to See and Get Copies of Your PHI",
      description: 'Other than "psychotherapy notes," you have the right to get an electronic or paper copy of your medical record and other information that I have about you. I will provide you with a copy of your record, or a summary of it, if you agree to receive a summary, within 30 days of receiving your written request, and I may charge a reasonable, cost-based fee for doing so.'
    },
    {
      icon: FileText,
      title: "The Right to Get a List of the Disclosures I Have Made",
      description: "You have the right to request a list of instances in which I have disclosed your PHI for purposes other than treatment, payment, or health care operations, or for which you provided me with an Authorization. I will respond to your request for an accounting of disclosures within 60 days of receiving your request."
    },
    {
      icon: Edit,
      title: "The Right to Correct or Update Your PHI",
      description: 'If you believe that there is a mistake in your PHI, or that a piece of important information is missing from your PHI, you have the right to request that I correct the existing information or add the missing information. I may say "no" to your request, but I will tell you why in writing within 60 days of receiving your request.'
    },
    {
      icon: Download,
      title: "The Right to Get a Paper or Electronic Copy of this Notice",
      description: "You have the right get a paper copy of this Notice, and you have the right to get a copy of this notice by e-mail. And, even if you have agreed to receive this Notice via e-mail, you also have the right to request a paper copy of it."
    }
  ];

  return (
    <>

      <div className="privacy-container">
        {/* Header */}
        <div className="privacy-header">
          <div className="privacy-header-content">
            <div className="privacy-header-icon-wrapper">
              <Shield className="privacy-header-icon" />
            </div>
            <h1 className="privacy-header-title">
              Privacy & Confidentiality
            </h1>
            <p className="privacy-header-subtitle">
              THIS NOTICE DESCRIBES HOW HEALTH INFORMATION MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.
            </p>
          </div>
        </div>

        {/* Main Content */}
        <div className="privacy-main-content">
          
          {/* Section I: Pledge */}
          <div className="privacy-section privacy-section-blue">
            <div className="privacy-section-header">
              <div className="privacy-icon-badge privacy-icon-badge-blue">
                <Shield className="privacy-section-icon" />
              </div>
              <h2 className="privacy-section-title">
                I. My Pledge Regarding Health Information
              </h2>
            </div>
            
            <div className="privacy-section-content">
              {sections[0].content.map((para, idx) => (
                <p key={idx} className="privacy-paragraph">{para}</p>
              ))}
              
              <div className="privacy-requirements-box">
                <h3 className="privacy-requirements-title">I am required by law to:</h3>
                <ul className="privacy-requirements-list">
                  {sections[0].requirements.map((req, idx) => (
                    <li key={idx} className="privacy-requirement-item">
                      <span className="privacy-bullet privacy-bullet-blue"></span>
                      <span className="privacy-requirement-text">{req}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Section II: Usage and Disclosure */}
          <div className="privacy-section privacy-section-indigo">
            <h2 className="privacy-section-title">
              II. How I May Use and Disclose Health Information About You
            </h2>
            
            <p className="privacy-intro-text">
              The following categories describe different ways that I use and disclose health information. For each category of uses or disclosures, I will explain what I mean and try to give some examples. Not every use or disclosure in a category will be listed. However, all of the ways I am permitted to use and disclose information will fall within one of the categories.
            </p>

            <div className="privacy-categories-wrapper">
              {usageCategories.map((category, idx) => (
                <div key={idx} className="privacy-category-card">
                  <h3 className="privacy-category-title">{category.title}</h3>
                  <p className="privacy-category-description">{category.description}</p>
                  <p className="privacy-category-details">{category.details}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Section III: Authorization Required */}
          <div className="privacy-section privacy-section-purple">
            <h2 className="privacy-section-title">
              III. Certain Uses and Disclosures Require Your Authorization
            </h2>

            <div className="privacy-auth-wrapper">
              {authorizationRequired.map((item, idx) => (
                <div key={idx} className="privacy-auth-card">
                  <h3 className="privacy-auth-title">{item.title}</h3>
                  {item.description && (
                    <p className="privacy-auth-description">{item.description}</p>
                  )}
                  {item.points && (
                    <div className="privacy-auth-points-wrapper">
                      <p className="privacy-auth-points-intro">
                        I do keep &quot;psychotherapy notes&quot; as that term is defined in 45 CFR § 164.501, and any use or disclosure of such notes requires your Authorization unless the use or disclosure is:
                      </p>
                      <ul className="privacy-auth-points-list">
                        {item.points.map((point, pIdx) => (
                          <li key={pIdx} className="privacy-auth-point-item">
                            <span className="privacy-bullet privacy-bullet-purple"></span>
                            <span className="privacy-auth-point-text">{point}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Section IV: No Authorization Required */}
          <div className="privacy-section privacy-section-green">
            <h2 className="privacy-section-title">
              IV. Certain Uses and Disclosures Do Not Require Your Authorization
            </h2>
            
            <p className="privacy-intro-text">
              Subject to certain limitations in the law, I can use and disclose your PHI without your Authorization for the following reasons:
            </p>

            <div className="privacy-no-auth-grid">
              {noAuthRequired.map((item, idx) => (
                <div key={idx} className="privacy-no-auth-item">
                  <span className="privacy-bullet privacy-bullet-green"></span>
                  <p className="privacy-no-auth-text">{item}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Section V: Opportunity to Object */}
          <div className="privacy-section privacy-section-yellow">
            <h2 className="privacy-section-title">
              V. Certain Uses and Disclosures Require You to Have the Opportunity to Object
            </h2>
            
            <div className="privacy-object-card">
              <h3 className="privacy-object-title">Disclosures to Family, Friends, or Others</h3>
              <p className="privacy-object-text">
                I may provide your PHI to a family member, friend, or other person that you indicate is involved in your care or the payment for your health care unless you object in whole or in part. The opportunity to consent may be obtained retroactively in emergency situations.
              </p>
            </div>
          </div>

          {/* Section VI: Your Rights */}
          <div className="privacy-section privacy-section-red">
            <h2 className="privacy-section-title privacy-rights-title">
              VI. You Have the Following Rights With Respect to Your PHI
            </h2>

            <div className="privacy-rights-grid">
              {yourRights.map((right, idx) => {
                const Icon = right.icon;
                return (
                  <div key={idx} className="privacy-right-card">
                    <div className="privacy-right-content">
                      <div className="privacy-right-icon-badge">
                        <Icon className="privacy-right-icon" />
                      </div>
                      <div className="privacy-right-text-wrapper">
                        <h3 className="privacy-right-title">{right.title}</h3>
                        <p className="privacy-right-description">{right.description}</p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Footer */}
          <div className="privacy-footer">
            <Lock className="privacy-footer-icon" />
            <p className="privacy-footer-text">
              Your privacy and confidentiality are our top priorities. If you have any questions about this notice, please don&apos;t hesitate to contact us.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}